---

- name: Create user
  ansible.builtin.user:
    name: zef
    create_home: true
    shell: /bin/bash
  tags:
    - user

- name: Copy SSH keys
  ansible.posix.authorized_key:
    user: zef
    state: present
    key: "https://github.com/{{ item }}.keys"
  loop: "{{ ssh_user }}"

- name: Deploy env file
  ansible.builtin.template:
    src: .env.j2
    dest: /home/zef/.env
    mode: "0600"
    owner: zef
  tags:
    - secret
